"""阶段一初始数据结构（冻结快照，不再导入运行时模型）。

已应用本迁移的数据库不重跑；新库只创建本版本的表，后续表由后续迁移创建。
Revision ID: 20260830_0001
"""
from alembic import op
import sqlalchemy as sa

revision = "20260830_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users'))
    )
    op.create_index(op.f('ix_admin_users_is_active'), 'admin_users', ['is_active'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('background_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_tasks'))
    )
    op.create_index(op.f('ix_background_tasks_status'), 'background_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_background_tasks_task_type'), 'background_tasks', ['task_type'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index(op.f('ix_categories_is_visible'), 'categories', ['is_visible'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_domain', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers'))
    )
    op.create_index(op.f('ix_providers_code'), 'providers', ['code'], unique=True)
    op.create_index(op.f('ix_providers_status'), 'providers', ['status'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_code', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('normalized_title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('translator', sa.String(length=255), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('isbn', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('publish_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('formats', sa.String(length=120), nullable=True),
    sa.Column('copyright_status', sa.String(length=30), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('publish_status', sa.String(length=30), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.String(length=500), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources'))
    )
    op.create_index(op.f('ix_resources_author'), 'resources', ['author'], unique=False)
    op.create_index(op.f('ix_resources_copyright_status'), 'resources', ['copyright_status'], unique=False)
    op.create_index(op.f('ix_resources_isbn'), 'resources', ['isbn'], unique=False)
    op.create_index(op.f('ix_resources_normalized_title'), 'resources', ['normalized_title'], unique=False)
    op.create_index(op.f('ix_resources_publish_status'), 'resources', ['publish_status'], unique=False)
    op.create_index(op.f('ix_resources_published_at'), 'resources', ['published_at'], unique=False)
    op.create_index(op.f('ix_resources_resource_code'), 'resources', ['resource_code'], unique=True)
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resources_slug'), 'resources', ['slug'], unique=True)
    op.create_index(op.f('ix_resources_title'), 'resources', ['title'], unique=False)
    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_query', sa.String(length=255), nullable=False),
    sa.Column('normalized_query', sa.String(length=255), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('searched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_queries'))
    )
    op.create_index(op.f('ix_search_queries_normalized_query'), 'search_queries', ['normalized_query'], unique=False)
    op.create_index(op.f('ix_search_queries_result_count'), 'search_queries', ['result_count'], unique=False)
    op.create_index(op.f('ix_search_queries_searched_at'), 'search_queries', ['searched_at'], unique=False)
    op.create_table('admin_operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], name=op.f('fk_admin_operation_logs_admin_user_id_admin_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_operation_logs'))
    )
    op.create_index(op.f('ix_admin_operation_logs_action'), 'admin_operation_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_operation_logs_admin_user_id'), 'admin_operation_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_operation_logs_created_at'), 'admin_operation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_operation_logs_entity_type'), 'admin_operation_logs', ['entity_type'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('ready_rows', sa.Integer(), nullable=False),
    sa.Column('warning_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('conflict_rows', sa.Integer(), nullable=False),
    sa.Column('committed_rows', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], name=op.f('fk_import_batches_created_by_id_admin_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    op.create_index(op.f('ix_import_batches_status'), 'import_batches', ['status'], unique=False)
    op.create_table('provider_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('credential_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_accounts_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_accounts'))
    )
    op.create_index(op.f('ix_provider_accounts_provider_id'), 'provider_accounts', ['provider_id'], unique=False)
    op.create_table('resource_categories',
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_resource_categories_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_categories_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', 'category_id', name=op.f('pk_resource_categories'))
    )
    op.create_table('resource_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_format', sa.String(length=30), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_files_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_files'))
    )
    op.create_index(op.f('ix_resource_files_checksum_sha256'), 'resource_files', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_resource_files_resource_id'), 'resource_files', ['resource_id'], unique=False)
    op.create_table('import_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_errors_batch_id_import_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_errors'))
    )
    op.create_index(op.f('ix_import_errors_batch_id'), 'import_errors', ['batch_id'], unique=False)
    op.create_index(op.f('ix_import_errors_error_code'), 'import_errors', ['error_code'], unique=False)
    op.create_table('import_raw_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('parsed_data', sa.JSON(), nullable=False),
    sa.Column('row_status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('normalized_url_hash', sa.String(length=64), nullable=True),
    sa.Column('matched_resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_raw_rows_batch_id_import_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_resource_id'], ['resources.id'], name=op.f('fk_import_raw_rows_matched_resource_id_resources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_raw_rows')),
    sa.UniqueConstraint('batch_id', 'row_number', name='uq_import_batch_row')
    )
    op.create_index(op.f('ix_import_raw_rows_batch_id'), 'import_raw_rows', ['batch_id'], unique=False)
    op.create_index(op.f('ix_import_raw_rows_normalized_url_hash'), 'import_raw_rows', ['normalized_url_hash'], unique=False)
    op.create_index(op.f('ix_import_raw_rows_row_status'), 'import_raw_rows', ['row_status'], unique=False)
    op.create_table('resource_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('provider_account_id', sa.Integer(), nullable=True),
    sa.Column('provider_file_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_account_id'], ['provider_accounts.id'], name=op.f('fk_resource_channels_provider_account_id_provider_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_resource_channels_provider_id_providers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_channels_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_channels')),
    sa.UniqueConstraint('resource_id', 'provider_id', name='uq_channel_resource_provider')
    )
    op.create_index(op.f('ix_resource_channels_provider_account_id'), 'resource_channels', ['provider_account_id'], unique=False)
    op.create_index(op.f('ix_resource_channels_provider_file_id'), 'resource_channels', ['provider_file_id'], unique=False)
    op.create_index(op.f('ix_resource_channels_provider_id'), 'resource_channels', ['provider_id'], unique=False)
    op.create_index(op.f('ix_resource_channels_resource_id'), 'resource_channels', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_channels_status'), 'resource_channels', ['status'], unique=False)
    op.create_table('channel_share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('provider_share_id', sa.String(length=255), nullable=False),
    sa.Column('share_url', sa.String(length=1000), nullable=False),
    sa.Column('normalized_url', sa.String(length=1000), nullable=False),
    sa.Column('normalized_url_hash', sa.String(length=64), nullable=False),
    sa.Column('extract_code', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['resource_channels.id'], name=op.f('fk_channel_share_links_channel_id_resource_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_channel_share_links_provider_id_providers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_share_links')),
    sa.UniqueConstraint('normalized_url_hash', name='uq_share_link_normalized_hash')
    )
    op.create_index(op.f('ix_channel_share_links_channel_id'), 'channel_share_links', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_share_links_is_visible'), 'channel_share_links', ['is_visible'], unique=False)
    op.create_index(op.f('ix_channel_share_links_provider_id'), 'channel_share_links', ['provider_id'], unique=False)
    op.create_index(op.f('ix_channel_share_links_provider_share_id'), 'channel_share_links', ['provider_share_id'], unique=False)
    op.create_index(op.f('ix_channel_share_links_status'), 'channel_share_links', ['status'], unique=False)
    op.create_index('ix_share_link_front_status', 'channel_share_links', ['is_visible', 'status', 'priority'], unique=False)
    op.create_table('link_check_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_link_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['share_link_id'], ['channel_share_links.id'], name=op.f('fk_link_check_logs_share_link_id_channel_share_links'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_link_check_logs'))
    )
    op.create_index(op.f('ix_link_check_logs_checked_at'), 'link_check_logs', ['checked_at'], unique=False)
    op.create_index(op.f('ix_link_check_logs_result'), 'link_check_logs', ['result'], unique=False)
    op.create_index(op.f('ix_link_check_logs_share_link_id'), 'link_check_logs', ['share_link_id'], unique=False)
    op.create_table('link_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_link_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('referer', sa.String(length=1000), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_link_clicks_provider_id_providers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_link_clicks_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_link_id'], ['channel_share_links.id'], name=op.f('fk_link_clicks_share_link_id_channel_share_links'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_link_clicks'))
    )
    op.create_index(op.f('ix_link_clicks_clicked_at'), 'link_clicks', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_link_clicks_provider_id'), 'link_clicks', ['provider_id'], unique=False)
    op.create_index(op.f('ix_link_clicks_resource_id'), 'link_clicks', ['resource_id'], unique=False)
    op.create_index(op.f('ix_link_clicks_share_link_id'), 'link_clicks', ['share_link_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_clicks_share_link_id'), table_name='link_clicks')
    op.drop_index(op.f('ix_link_clicks_resource_id'), table_name='link_clicks')
    op.drop_index(op.f('ix_link_clicks_provider_id'), table_name='link_clicks')
    op.drop_index(op.f('ix_link_clicks_clicked_at'), table_name='link_clicks')
    op.drop_table('link_clicks')
    op.drop_index(op.f('ix_link_check_logs_share_link_id'), table_name='link_check_logs')
    op.drop_index(op.f('ix_link_check_logs_result'), table_name='link_check_logs')
    op.drop_index(op.f('ix_link_check_logs_checked_at'), table_name='link_check_logs')
    op.drop_table('link_check_logs')
    op.drop_index('ix_share_link_front_status', table_name='channel_share_links')
    op.drop_index(op.f('ix_channel_share_links_status'), table_name='channel_share_links')
    op.drop_index(op.f('ix_channel_share_links_provider_share_id'), table_name='channel_share_links')
    op.drop_index(op.f('ix_channel_share_links_provider_id'), table_name='channel_share_links')
    op.drop_index(op.f('ix_channel_share_links_is_visible'), table_name='channel_share_links')
    op.drop_index(op.f('ix_channel_share_links_channel_id'), table_name='channel_share_links')
    op.drop_table('channel_share_links')
    op.drop_index(op.f('ix_resource_channels_status'), table_name='resource_channels')
    op.drop_index(op.f('ix_resource_channels_resource_id'), table_name='resource_channels')
    op.drop_index(op.f('ix_resource_channels_provider_id'), table_name='resource_channels')
    op.drop_index(op.f('ix_resource_channels_provider_file_id'), table_name='resource_channels')
    op.drop_index(op.f('ix_resource_channels_provider_account_id'), table_name='resource_channels')
    op.drop_table('resource_channels')
    op.drop_index(op.f('ix_import_raw_rows_row_status'), table_name='import_raw_rows')
    op.drop_index(op.f('ix_import_raw_rows_normalized_url_hash'), table_name='import_raw_rows')
    op.drop_index(op.f('ix_import_raw_rows_batch_id'), table_name='import_raw_rows')
    op.drop_table('import_raw_rows')
    op.drop_index(op.f('ix_import_errors_error_code'), table_name='import_errors')
    op.drop_index(op.f('ix_import_errors_batch_id'), table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index(op.f('ix_resource_files_resource_id'), table_name='resource_files')
    op.drop_index(op.f('ix_resource_files_checksum_sha256'), table_name='resource_files')
    op.drop_table('resource_files')
    op.drop_table('resource_categories')
    op.drop_index(op.f('ix_provider_accounts_provider_id'), table_name='provider_accounts')
    op.drop_table('provider_accounts')
    op.drop_index(op.f('ix_import_batches_status'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_admin_operation_logs_entity_type'), table_name='admin_operation_logs')
    op.drop_index(op.f('ix_admin_operation_logs_created_at'), table_name='admin_operation_logs')
    op.drop_index(op.f('ix_admin_operation_logs_admin_user_id'), table_name='admin_operation_logs')
    op.drop_index(op.f('ix_admin_operation_logs_action'), table_name='admin_operation_logs')
    op.drop_table('admin_operation_logs')
    op.drop_index(op.f('ix_search_queries_searched_at'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_result_count'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_normalized_query'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_resources_title'), table_name='resources')
    op.drop_index(op.f('ix_resources_slug'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_code'), table_name='resources')
    op.drop_index(op.f('ix_resources_published_at'), table_name='resources')
    op.drop_index(op.f('ix_resources_publish_status'), table_name='resources')
    op.drop_index(op.f('ix_resources_normalized_title'), table_name='resources')
    op.drop_index(op.f('ix_resources_isbn'), table_name='resources')
    op.drop_index(op.f('ix_resources_copyright_status'), table_name='resources')
    op.drop_index(op.f('ix_resources_author'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_providers_status'), table_name='providers')
    op.drop_index(op.f('ix_providers_code'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_visible'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_background_tasks_task_type'), table_name='background_tasks')
    op.drop_index(op.f('ix_background_tasks_status'), table_name='background_tasks')
    op.drop_table('background_tasks')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_is_active'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
