"""add friend_links

Revision ID: 51108abe030f
Revises: 20260830_0002
Create Date: 2026-08-31 01:26:11.870673
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '51108abe030f'
down_revision: Union[str, Sequence[str], None] = '20260830_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friend_links'))
    )
    op.create_index('ix_friend_link_visible_sort', 'friend_links', ['is_visible', 'sort_order'], unique=False)
    op.create_index(op.f('ix_friend_links_created_at'), 'friend_links', ['created_at'], unique=False)
    op.create_index(op.f('ix_friend_links_is_visible'), 'friend_links', ['is_visible'], unique=False)
    op.create_index(op.f('ix_friend_links_updated_at'), 'friend_links', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friend_links_updated_at'), table_name='friend_links')
    op.drop_index(op.f('ix_friend_links_is_visible'), table_name='friend_links')
    op.drop_index(op.f('ix_friend_links_created_at'), table_name='friend_links')
    op.drop_index('ix_friend_link_visible_sort', table_name='friend_links')
    op.drop_table('friend_links')
    # ### end Alembic commands ###
